# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-15 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('formadepago', models.CharField(max_length=30)),
            ],
        ),
    ]
